INSERT INTO APPOINTMENT (NAME, DATE_TIME, PERSON_ID)
VALUES ('Battles of Lexington and Concord', PARSEDATETIME('1775-04-19 07:00:00 EST', 'yyyy-MM-dd HH:mm:ss z'), 2);
INSERT INTO APPOINTMENT (NAME, DATE_TIME, PERSON_ID)
VALUES ('Siege of Boston', PARSEDATETIME('1775-04-19 12:00:00 EST', 'yyyy-MM-dd HH:mm:ss z'), 1);