CREATE TABLE APPOINTMENT (
  APPOINTMENT_ID BIGINT AUTO_INCREMENT PRIMARY KEY,
  NAME           VARCHAR,
  DATE_TIME      TIMESTAMP,
  PERSON_ID      BIGINT
);
CREATE INDEX PERSON_APPOINTMENT ON APPOINTMENT (PERSON_ID);